### ISSUE TITLE
Controller doesn't show in Steam Client Beta settings, works in release

### ISSUE THREAD

**Issue by CrazyCoder** [philipellisis/virtual-pinball-board-configurator#1]
Getting this error:

```
Cannot read property 'nControllerIndex' of undefined
```

It's likely a Steam bug, but you may want to check it and report to Steam developers so that it doesn't break your controller in the next update.

![Screenshot 2023-09-16 155323](https://github.com/philipellisis/virtual-pinball-board-configurator/assets/122834/6632c5ac-8f62-44b2-9cce-421d49330d4b)

**Comment by philipellisis** [comment]
Created bug ticket: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3887225762856884376/
