### ISSUE TITLE
"Save Config Success" dialog displayed multiple times

### ISSUE THREAD

**Issue by CrazyCoder** [philipellisis/virtual-pinball-board-configurator#3]
See the attached video to reproduce.

The more times you reopen the configuration settings and upload config, the more times notification is displayed until you disconnect and connect again (which resets the count).

https://github.com/philipellisis/virtual-pinball-board-configurator/assets/122834/bc75c238-5527-4e48-a836-04cf1c204a49

I'd suggest displaying a non-modal notification somewhere for a better usability.

**Comment by philipellisis** [comment]
Fixed in latest changeset [c0e409fd04dc1731f91d5846bdd61209cc3fe6b6](https://github.com/philipellisis/virtual-pinball-board-configurator/commit/c0e409fd04dc1731f91d5846bdd61209cc3fe6b6)
