### ISSUE TITLE
Remove unused/obsolete joystick.ino.hex from the repository

### ISSUE THREAD

**Issue by CrazyCoder** [philipellisis/virtual-pinball-board-configurator#4]
~~The new firmware is in `PinOne.ino.hex`, but the code is using `joystick.ino.hex` in AVRDude arguments~~.

EDIT: sorry, the correct firmware is flashed, you just need to remove `joystick.ino.hex` from the repository.

By the way, I was trying to build the current code to test something and it exceeds the flash size. What tricks do you use to fit it? Some specific/older dependencies/libraries that take less space? Or maybe you are using the older IDE/gcc versions?

```
Using library Joystick at version 2.1.1 in folder: C:\Users\serge\Documents\Arduino\libraries\Joystick 
Using library Adafruit PWM Servo Driver Library at version 3.0.1 in folder: C:\Users\serge\Documents\Arduino\libraries\Adafruit_PWM_Servo_Driver_Library 
Using library Adafruit BusIO at version 1.14.4 in folder: C:\Users\serge\Documents\Arduino\libraries\Adafruit_BusIO 
Using library Wire at version 1.0 in folder: C:\Users\serge\AppData\Local\arduino15\packages\arduino\hardware\avr\1.8.6\libraries\Wire 
Using library Adafruit MPU6050 at version 2.2.4 in folder: C:\Users\serge\Documents\Arduino\libraries\Adafruit_MPU6050 
Using library SPI at version 1.0 in folder: C:\Users\serge\AppData\Local\arduino15\packages\arduino\hardware\avr\1.8.6\libraries\SPI 
Using library Adafruit Unified Sensor at version 1.1.12 in folder: C:\Users\serge\Documents\Arduino\libraries\Adafruit_Unified_Sensor 
Using library EEPROM at version 2.0 in folder: C:\Users\serge\AppData\Local\arduino15\packages\arduino\hardware\avr\1.8.6\libraries\EEPROM 
"C:\\Users\\serge\\AppData\\Local\\arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino7/bin/avr-size" -A "C:\\Users\\serge\\AppData\\Local\\Temp\\arduino\\sketches\\036F4B9238D75AA1E713FB69B6B93764/PinOne.ino.elf"
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
Sketch uses 28730 bytes (100%) of program storage space. Maximum is 28672 bytes.
Global variables use 1784 bytes (69%) of dynamic memory, leaving 776 bytes for local variables. Maximum is 2560 bytes.
text section exceeds available space in board

Compilation error: text section exceeds available space in board
```

This is when using Leonardo as the board. If I switch to Micro, the shortage is even worse (by two bytes):

```
Sketch uses 28732 bytes (100%) of program storage space. Maximum is 28672 bytes.
```

Should I use Leonardo or Micro?

**Comment by philipellisis** [comment]
Micro is the one to use, but the codebase is getting close to maximum size. I am actually working on making the codebase smaller by minimizing the dependencies so if you can wait a few weeks there will be a bundle size much smaller to use, or you can compile and install without the bootloader to free up space.

**Comment by CrazyCoder** [comment]
I won't be able to flash/update the code via USB if I omit the bootloader, so it doesn't look like a viable option :)

**Comment by CrazyCoder** [comment]
I managed to fit the firmware by editing the Adafruit MPU6050 library and removing the string constants:

```
MPU6050_T
MPU6050_A
MPU6050_G
```

You can also save a couple of bytes by placing the omitted `F()` in `Plunger.cpp` so that it becomes `Serial.print(F("\r\n"));`.

**Comment by CrazyCoder** [comment]
Update button saves firmware from resource `PinOne.ino.hex` into `joystick.ino.hex`, so it flashes the correct one. I was confused by the presence of `joystick.ino.hex` in the Git repository. It should be removed.

**Comment by philipellisis** [comment]
fixed with https://github.com/philipellisis/virtual-pinball-board-configurator/commit/3504d38bc9634c838a3023a738ad3b38842c9f16
